import fs from "node:fs";
import vm from "node:vm";
import assert from "node:assert/strict";
const code=fs.readFileSync(new URL("../Bambulab-Dashboard.js", import.meta.url),"utf8");
const marker="class BambuLabDashboard extends HTMLElement";
const prelude=code.slice(0,code.indexOf(marker));
const context={console,Intl,URL}; vm.createContext(context);
vm.runInContext(`${prelude}\nthis.__test={buildPrinterModels,printerArtworkUrl,entryMatchesAlias};`,context);
const {buildPrinterModels,printerArtworkUrl,entryMatchesAlias}=context.__test;
const devices=[{id:'p',manufacturer:'Bambu Lab',model:'P1S',name:'P1S',via_device_id:null},{id:'ams',manufacturer:'Bambu Lab',model:'AMS',name:'AMS',via_device_id:'p'}];
const entities=[{entity_id:'sensor.p_progress',platform:'bambu_lab',device_id:'p',translation_key:'print_progress',unique_id:'S_print_progress'},{entity_id:'sensor.p_bed',platform:'bambu_lab',device_id:'p',translation_key:'bed_temp',unique_id:'S_bed_temp'},{entity_id:'sensor.ams_tray',platform:'bambu_lab',device_id:'ams',translation_key:'tray',unique_id:'S_AMS_TRAY'}];
const models=buildPrinterModels(devices,entities); assert.equal(models.length,1); assert.equal(models[0].id,'p');
assert.equal(entryMatchesAlias({translation_key:'printing_speed',unique_id:'S_Speed'},'printing_speed'),true);
assert.ok(printerArtworkUrl(devices[0]).endsWith('/P1S.png'));
assert.equal(printerArtworkUrl({...devices[0],model:'A2L'}),null);
console.log('discovery tests: ok');
