import fs from "node:fs";
import assert from "node:assert/strict";
const code=fs.readFileSync(new URL("../Bambulab-Dashboard.js", import.meta.url),"utf8");
assert.match(code,/const VERSION = "1\.3\.0"/);
assert.match(code,/_isInCardPicker/);
assert.match(code,/preview: true/);
assert.match(code,/data-open-printer=/);
assert.match(code,/ha-entity-picker/);
assert.match(code,/data-spool-entity/);
assert.match(code,/hass-more-info/);
assert.match(code,/target_nozzle_temperature/);
assert.match(code,/data-fan-entity/);
assert.match(code,/printing_speed/);
assert.match(code,/data-theme/);
assert.match(code,/theme-light/);
assert.match(code,/object-fit:contain/);
assert.match(code,/_captureScrollState/);
assert.match(code,/_renderCurrentPrint/);
assert.match(code,/total_usage_hours/);
assert.doesNotMatch(code,/image_url/);
assert.doesNotMatch(code,/"A2L"\s*:\s*"A1\.png"/);
console.log("feature/static tests: ok");
