import fs from "node:fs";
import assert from "node:assert/strict";
const code=fs.readFileSync(new URL("../Bambulab-Dashboard.js", import.meta.url),"utf8");
assert.match(code,/const VERSION = "1\.2\.0"/);
assert.match(code,/data-open-printer=/,"printer switch must use direct detail navigation");
assert.match(code,/image_url/,"custom printer image setting missing");
assert.match(code,/progress_entity/,"manual entity overrides missing");
assert.match(code,/sensor-entity-ids/,"unfiltered sensor datalist missing");
assert.match(code,/ExternalSpool|external\\s\*spool/i,"AMS helper-device filtering missing");
assert.match(code,/\.shell \{ width:100%; max-width:none;/,"internal max width must be removed");
assert.doesNotMatch(code,/"A2L"\s*:\s*"A1\.png"/,"wrong A2L-to-A1 artwork fallback must not return");
assert.match(code,/preview: false/,"card picker full preview should stay disabled");
console.log("feature/static tests: ok");
